### PR TITLE
update sasToken implementation

### PR DESCRIPTION
**Pull request by jakeFeldman**

### CODE REVIEW

**Comment by devendra-rgb** [comment]
@jakeFeldman  Oh you updated cool hope it helps users from now to access data using SAS which will increase more security level : )

**Comment by jakeFeldman** [comment]
Yes, but images still don't render inside of the strapi dashboard. Were you able to figure out why?

**Comment by gevera** [comment]
Facing the same issue. Images are not displayed in the Strapi's Media Library even thought they have been uploaded to the Blob storage and if you inspect the element and open the image in the new tab, the image is being displayed

**Comment by jakeFeldman** [comment]
@gevera Are you using the account/account key method?

**Comment by devendra-rgb** [comment]
@jakeFeldman  are you facing this issue only with SAS Token or with account key also ?

**Comment by jakeFeldman** [comment]
I only see it with `sasToken`

**Pull request merged**
