### PR TITLE
Add option for additional image formats webp and avif

### PR DESCRIPTION
**Pull request by f-masche**
Adds option to create additional image formats on upload #47.

To include the image on a website you can use it similar to this:
```html

<picture>
  <source type="image/webp" srcset="{image.formats.small.webpUrl}">
  <source type="image/avif" srcset="{image.formats.small.avifUrl}">
  <img src="{image.formats.small.url}">
</picture>

or for the original

<picture>
  <source type="image/webp" srcset="{image.provider_metadata.webpUrl}">
  <source type="image/avif" srcset="{image.provider_metadata.avifUrl}">
  <img src="{image.url}">
</picture>
```

### CODE REVIEW

**Comment by jakeFeldman** [comment]
Thanks for the PR @f-masche. I'll be able to review this later today or early tomorrow.

**Review by jakeFeldman — COMMENTED** [review]
Changes look good. Could you attach a video of uploads, reads and deletions working?

**Comment by f-masche** [comment]
Here are two videos showing the feature: 
First video is showing upload and using image in strapi + api response. 
Second video is showing write and deletions in the azure cdn.


https://user-images.githubusercontent.com/2787357/174562057-11f0f8e1-e3da-4d38-8203-749ba040323a.mp4

https://user-images.githubusercontent.com/2787357/174562047-6272aeaf-57f4-4344-ade5-0223039f9625.mp4

**Comment by jakeFeldman** [comment]
@f-masche this looks good to me. When you have a minute to resolve the merge conflicts I'll do a pass over again and then get this version published. Thanks again!!

**Comment by jakeFeldman** [comment]
@f-masche is this something you still want to get it? If so, please resolve the conflicts and we can merge and push a new version. Thanks!

**Pull request closed without merging**
